<?php

namespace Yat\blogNewBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticles()
    {
        $query = $this->createQueryBuilder('a')
                      ->leftJoin('a.image', 'i')//On joint sur l'attribut image
                      ->addSelect('i')
                      ->leftJoint('a.categories', 'c') //On joint l'attribut categorie
                      ->addSelect('c')
                      ->orderBy('a.date', 'DESC')
                      ->getQuery();
                      
        return $query->getResult();
    }
}
