<?php
namespace Yat\blogNewBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\DataFixtures\ReferenceRepository;

/**
 *This class was generated by docrine, add your own custom
 *repository methods below
 */

 class ArticleRepository extends EntityRepository
 {
 }
 