blog_new_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogNewBundle:Default:index }
    
yatblog_accueil:
    path:     /{page}
    defaults: { _controller: BlogNewBundle:Blog:index, page: 1 }
    requirements:
        page: \d*

yatblog_voir:
    path:     /article/{id}
    defaults: { _controller: BlogNewBundle:Blog:voir }
    requirements:
        id: \d+

yatblog_modifier:
    path:     /modifier/{id}
    defaults: { _controller: BlogNewBundle:Blog:modifier }
    requirements:
        id: \d+

yatblog_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: BlogNewBundle:Blog:supprimer }
    requirements:
        id: \d+

yatblog_voir_slug:
    path:     /{annee}/{slug}.{format}
    defaults: { _controller: BlogNewBundle:Blog:voirSlug, format: html }
    requirements:
        annee:  \d{4}
        format: html|xml

yatblog_ajouter:
    path:     /ajouter
    defaults: { _controller: BlogNewBundle:Blog:ajouter }
